---
- name: Clean Directory for this project
  file:
    path: "{{ target_dir }}/datagen/"
    state: absent

- name: Create Directory for this project
  file:
    path: "{{ target_dir }}/datagen/"
    state: directory
    mode: '0755'

- name: Create Model Directory
  file:
    path: "{{ target_dir }}/datagen/models/"
    state: directory
    mode: '0755'

- name: Create Extra Data Directory
  file:
    path: "{{ target_dir }}/datagen/extra_data/"
    state: directory
    mode: '0755'


- name: Copy models to machine
  copy: 
    src: "{{ role_path }}/models/"
    dest: "{{ target_dir }}/datagen/models/"

- name: Copy extra_data files
  copy: 
    src: "{{ role_path }}/extra_data/"
    dest: "{{ target_dir }}/datagen/extra_data/"


- name: Set permissions for Extra Data Directory
  file:
    path: "{{ target_dir }}/datagen/extra_data/"
    state: directory
    mode: '0775'
    owner: datagen
    group: datagen
    recurse: yes

- name: Set permissions for Models Directory
  file:
    path: "{{ target_dir }}/datagen/models/"
    state: directory
    mode: '0775'
    owner: datagen
    group: datagen
    recurse: yes