---
models:
  # - file_name: full-model.json # Model File name presents in roles/data_gen/models (See README to know how to add models file)
  #   sinks: [hdfs-parquet, hbase, hive] # A list of sinks where to produce data among: hdfs-parquet, hdfs-orc, hdfs-avro, hdfs-csv, hdfs-json, hbase, hive, kafka, kudu, ozone, solr
  #   number_of_rows: 1000 # Number of rows to produce on each batch
  #   number_of_batches: 3 # Number of batch that program will launch a generation of data
  #   frequency:  # Frequency if need to schedule the job
        # minute: "*/5"
        # hour: "*"
        # day: "*"
  #   scheduler: none # To schedule the job according to cron-frequency set above using either 'cron' or 'oozie', 'none' will no schedule

  - file_name: full-model.json 
    sinks: [hdfs-parquet, hdfs-orc, hdfs-avro, hdfs-csv, hdfs-json, hbase, hive, kafka, ozone, solr] 
    number_of_rows: 1000
    number_of_batches: 2 

  - file_name: finance-transaction-model.json 
    sinks: [kafka] 
    number_of_rows: 1000
    number_of_batches: 1
    frequency: 
      minute: "*/5"
      hour: "*"
      day: "*"
    scheduler: cron
    

# Add other models' file (check README for syntax) and sinks like examples above