---
models:
  # - file_name: full-model.json # Model File name presents in roles/data_gen/models (See README to know how to add models file)
  #   sinks: [hdfs-parquet, hbase, hive] # A list of sinks where to produce data among: 
  #     hdfs-parquet, hdfs-orc, hdfs-json, hdfs-avro, hdfs-csv, hdfs-json, hbase, hive, kafka, kudu, ozone-parquet, ozone-orc, ozone-json, ozone-avro, ozone-csv, ozone-json, solr
  #   number_of_rows: 1000 # Number of rows to produce on each batch
  #   number_of_batches: 3 # Number of batch that program will launch a generation of data
  #   interval: 100 # Interval between two launches (used only if scheduled is true)
  #   scheduled: false # To schedule the job on an interval basis

  - file_name: customer-model.json 
    sinks: [hdfs-parquet, hive] 
    number_of_rows: 10000
    number_of_batches: 1 
    threads: 1

  - file_name: transaction-model.json 
    sinks: [kafka] 
    number_of_rows: 100
    number_of_batches: 10 
    interval: 100
    threads: 1
    scheduled: true
