---
ranger_policies:
  # - name: "HDFS Policy for francois" # Name of the policy
  #   type: hdfs # To which services it should create the policies: hdfs, hive, hbase, kafka, nifi, kudu, solr, schema-registry, yarn
  #   users: ["francois"] # A list a users that will be granted access to these resources
  #   resources: ["/tmp/", "/home/adrian"] # A list of resources which are: 
  #     paths for hdfs or ozone, databases for hive or kudu, topics for kafka, collections for solr, queues for yarn, resources for nifi, schema for schema-registry

# Add other policies below in the same way than the one above   

  - name: "HDFS Policy for adrian"
    type: hdfs
    users: ["adrian"]
    resources: ["/tmp/", "/home/adrian"]

  - name: "HDFS Policy for anoop"
    type: hdfs
    users: ["anoop"]
    resources: ["/tmp/", "/home/anoop"]

  - name: "Hbase Policy for anoop"
    type: hbase
    users: ["anoop", "datagen"]
    resources: ["banking:*"]  

  - name: "Hbase Policy for adrian"
    type: hbase
    users: ["adrian", "datagen"]
    resources: ["finance:*"] 

  - name: "Hive Policy for anoop"
    type: hive
    users: ["anoop", "datagen"]
    resources: ["banking*"]  

  - name: "Hive Policy for adrian"
    type: hive
    users: ["adrian", "datagen"]
    resources: ["finance*"] 

  - name: "Kafka Policy for anoop"
    type: kafka
    users: ["anoop", "datagen"]
    resources: ["banking*"]  

  - name: "Kafka Policy for adrian"
    type: kafka
    users: ["adrian", "datagen"]
    resources: ["finance*"] 

  - name: "Kudu Policy for anoop"
    type: kudu
    users: ["anoop", "datagen"]
    resources: ["banking*"]  

  - name: "Kudu Policy for adrian"
    type: kudu
    users: ["adrian", "datagen"]
    resources: ["finance*"] 

  - name: "Nifi Policy for francois"
    type: nifi
    users: ["francois"]
    resources: ["/*"]  

  - name: "Ozone Policy for anoop"
    type: ozone
    users: ["anoop", "datagen"]
    resources: ["banking*"]  

  - name: "Ozone Policy for adrian"
    type: ozone
    users: ["adrian", "datagen"]
    resources: ["finance*"] 

  - name: "SR Policy for anoop"
    type: schema-registry
    users: ["anoop", "datagen"]
    resources: ["banking*"]  

  - name: "SR Policy for adrian"
    type: schema-registry
    users: ["adrian", "datagen"]
    resources: ["finance*"] 

  - name: "SolR Policy for anoop"
    type: solr
    users: ["anoop", "datagen"]
    resources: ["banking*"]  

  - name: "SolR Policy for adrian"
    type: solr
    users: ["adrian", "datagen"]
    resources: ["finance*"] 

  - name: "YARN Policy for francois"
    type: yarn
    users: ["francois", "datagen"]
    resources: ["root.default", "root.datagen"]  



