---
users:
  - name: superman
    local_dir: /home/superman # default is /home/{{ name }}
    hdfs_dir: /user/superman # default is /user/{{ name }}
    use_keytab: true # default is true
    password: Cloudera1234 # default is Cloudera1234
    groups: ["hadoop"] # default is user name

# Add other users below in the same way than the one above

  - name: batman

