---
- name: Create Directory for projects
  file:
    path: "{{ target_dir }}/"
    state: directory
    mode: '0755'
  ignore_errors: true

- name: Install Maven
  package:
    name: maven
    state: present

- name: Install Git
  package:
    name: git
    state: present    

- name: Install Python 3
  package:
    name: python3
    state: present

- name: Install Pip 3
  package:
    name: python3-pip
    state: present