---
# TODO: Transform this as API call

- set_fact: 
    datagen_url: "{{ dg_protocol }}://{{ edge_host }}:{{ dg_port }}"

- name: DEBUG - datagen_url
  debug:
    msg: "{{ datagen_url }}"
  when: debug | default(false)

- set_fact:
    sink_list_for_api: "{% for sink in model.sinks %}&sink={{ sink }}{% endfor %}"  

- set_fact:
    model_file_path: "{{ target_dir }}/datagen/models/{{ model.file_name }}"

- set_fact:
    model_file_path_for_api: "{{ model_file_path | replace('/','%2F') }}"  

- set_fact:
    batches: "1"
  when: model.number_of_batches is not defined

- set_fact:
    batches: "{{ model.number_of_batches }}"
  when: model.number_of_batches is defined

- set_fact:
    rows: "10"
  when: model.number_of_rows is not defined

- set_fact:
    rows: "{{ model.number_of_rows }}"
  when: model.number_of_rows is defined  

- set_fact:
    threads: "1"
  when: model.threads is not defined

- set_fact:
    threads: "{{ model.threads }}"
  when: model.threads is defined  

- set_fact:
    interval: "360"
  when: model.interval is not defined

- set_fact:
    interval: "{{ model.interval }}"
  when: model.interval is defined  

- set_fact:
    scheduled: "false"
  when: model.scheduled is not defined

- set_fact:
    scheduled: "{{ model.scheduled }}"
  when: model.scheduled is defined  
  
  
- name: Launch Data Generation
  uri: 
    url: "{{ datagen_url }}/datagen/multiplesinks?batches={{ batches }}&rows={{ rows }}&model={{ model_file_path_for_api }}&threads={{ threads }}{{ sink_list_for_api }}"
    method: POST
    user: "{{ datagen_user }}"
    password: "{{ datagen_password }}"
    return_content: yes
    body_format: json
    status_code: 200
    validate_certs: no
    force_basic_auth: yes
  when: scheduled == "false"


- name: Schedule Data Generation
  uri: 
    url: "{{ datagen_url }}/datagen/multiplesinks?batches={{ batches }}&rows={{ rows }}&model={{ model_file_path_for_api }}&threads={{ threads }}&delay_between_executions_seconds={{ interval }}&scheduled=true&{{ sink_list_for_api }}"
    method: POST
    user: "{{ datagen_user }}"
    password: "{{ datagen_password }}"
    return_content: yes
    body_format: json
    status_code: 200
    validate_certs: no
    force_basic_auth: yes
  when: scheduled == "true"