---
# Create random-datagen.jar using a git clone and a mvn clean package
- name: Clone Repository
  git:
    repo: "{{ data_gen_git_url }}"
    dest: "{{ target_dir }}/random-datagen/git-repo/"
    version: "{{ data_gen_git_branch }}"
  when: data_gen_use_git   

- name: Clean & Package Project
  command:
    cmd: mvn clean package
    chdir: "{{ target_dir }}/random-datagen/git-repo/"
  when: data_gen_use_git

- name: Find jar compiled
  find:
    paths: "{{ target_dir }}/random-datagen/git-repo/target/"
    patterns: 'random-datagen*.jar'
  register: jar_compiled

- name: Get Jar from Compilation
  copy:
    src: "{{ jar_compiled.files[0].path }}"
    dest: "{{ target_dir }}/random-datagen/random-datagen.jar"
    remote_src: yes
  when: data_gen_use_git

# Get random-datagen.jar from already compiled versions
- set_fact:
    release_url: "https://github.com/frischHWC/random-datagen/releases/download/CDP-{{ cdp_version }}/random-datagen-CDP-{{ cdp_version }}.tar.gz"
  when: release_url is not defined and not data_gen_use_git

- name: Get random datagen jar and files
  get_url:
    url: "{{ release_url }}"
    dest: "{{ target_dir }}/random-datagen.tar.gz"
  when: not data_gen_use_git

- name: Untar project
  unarchive:
    src: "{{ target_dir }}/random-datagen.tar.gz"
    dest: "{{ target_dir }}/random-datagen/"
    remote_src: yes
  when: not data_gen_use_git

- name: Get Jar from Untar
  copy:
    src: "{{ target_dir }}/random-datagen/Users/frisch/random-datagen/random-datagencp.jar"
    dest: "{{ target_dir }}/random-datagen/random-datagen.jar"
    remote_src: yes
  when: not data_gen_use_git

- name: Clean untar Directory
  file:
    path: "{{ target_dir }}/random-datagen/Users/"
    state: absent
  when: not data_gen_use_git


# Set config.properties file
- name: Copy config.properties
  copy:
    src: /tmp/config-rd.properties 
    dest: "{{ target_dir }}/random-datagen/config.properties"
    remote_src: yes

- name: Clean config file
  file:
    path: /tmp/config-rd.properties
    state: absent    