---
### GET Hive CONFIGS ###

- set_fact:
    hive_service_name: "{{ cloudera_manager_all_services.json | community.general.json_query(query) }}"
  vars:
    query: "items[?type == 'HIVE_ON_TEZ'].name | [0]"

- name: DEBUG - hive_service_name
  debug:
    msg: "{{ hive_service_name }}"
  when: debug | default(false)


- name: Get Hive full config
  uri:
    url: "{{ cloudera_manager_api_url }}/clusters/{{ cluster_name }}/services/{{ hive_service_name }}/config?view=full"
    user: "{{ cloudera_manager_user }}"
    password: "{{ cloudera_manager_password }}"
    method: GET
    force_basic_auth: yes
    status_code: 200
    return_content: yes
    validate_certs: no
    body_format: json
  register: hive_full_config

### SET Hive CONFIGS ###
    
- set_fact:
    hive_zk_namespace: "{{ hive_full_config.json | community.general.json_query(query) }}"
  vars:
    query: "items[?name == 'hive_server2_zookeeper_namespace'].value | [0]"

- set_fact:
    hive_zk_namespace: "{{ hive_full_config.json | community.general.json_query(query) }}"
  vars:
    query: "items[?name == 'hive_server2_zookeeper_namespace'].default | [0]"
  when: hive_zk_namespace == ''

- name: DEBUG - hive_zk_namespace
  debug:
    msg: "{{ hive_zk_namespace }}"
  when: debug | default(false)  
    
- set_fact:
    tez_queue_name: "root.default"
  when: tez_queue_name is not defined

- name: DEBUG - tez_queue_name
  debug:
    msg: "{{ tez_queue_name }}"
  when: debug | default(false)  


# Kerberos
- set_fact:
    hive_kerberos: hdfs_kerberos

- name: DEBUG - hive_kerberos
  debug:
    msg: "{{ hive_kerberos }}"
  when: debug | default(false)  

# TLS
- set_fact:
    hive_tls: "{{ hive_full_config.json | community.general.json_query(query) }}"
  vars:
    query: "items[?name == 'hiveserver2_enable_ssl'].value | [0]"

- set_fact:
    hive_tls: "{{ hive_full_config.json | community.general.json_query(query) }}"
  vars:
    query: "items[?name == 'hiveserver2_enable_ssl'].default | [0]"
  when: hive_tls == ''

- name: DEBUG - hive_tls
  debug:
    msg: "{{ hive_tls }}"
  when: debug | default(false)  

- set_fact:
    hive_jdbc_url: "jdbc:hive2://{{ zk_quorum_with_port }}/default;principal=hive/_HOST@{{ krb_realm }};serviceDiscoveryMode=zooKeeper;zooKeeperNamespace={{ hive_zk_namespace }};ssl=true;sslTrustStore={{ truststore_location }};trustStorePassword={{ truststore_password }};"
  when: hive_jdbc_url is not defined and hive_kerberos and hive_tls

- set_fact:
    hive_jdbc_url: "jdbc:hive2://{{ zk_quorum_with_port }}/default;principal=hive/_HOST@{{ krb_realm }};serviceDiscoveryMode=zooKeeper;zooKeeperNamespace={{ hive_zk_namespace }};"
  when: hive_jdbc_url is not defined and hive_kerberos

- set_fact:
    hive_jdbc_url: "jdbc:hive2://{{ zk_quorum_with_port }}/default;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace={{ hive_zk_namespace }};"
  when: hive_jdbc_url is not defined

- name: DEBUG - hive_jdbc_url
  debug:
    msg: "{{ hive_jdbc_url }}"
  when: debug | default(false)  
