---
###########################################
############# DATA GENERATION #############

- name: Get Datagen configs
  hosts: edge
  gather_facts: false
  roles: 
    - auto_configure/cm-config
    - data_gen/get_dg_info

- name: Data Generation 
  hosts: edge
  gather_facts: false
  tasks:
    - name: Run Data Generation foreach model
      include_role:
        name: data_gen/generate_data
      vars:
        model: "{{ item }}"
      with_items: "{{ models }}"
  tags:
    - data
