---
###########################################
############# RANGER POLICIES #############

- name: Get Ranger configuration
  hosts: cloudera_manager
  gather_facts: false
  roles: 
    - auto_configure/cm-config
    - auto_configure/all-config
    - { role: auto_configure/ranger-config, when: config_ranger }
  tags:
    - ranger  

- name: Ranger Policies
  hosts: cloudera_manager
  gather_facts: false
  tasks:
    - name: push ranger policies
      include_role:
        name: ranger_policies/
      with_items: "{{ ranger_policies }}"
      loop_control:
        loop_var: policy
  tags:
    - ranger  